# Generated by Django 5.1.6 on 2026-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language_fk_and_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='comments',
            field=models.TextField(
                blank=True, help_text='Comment must be <200 characters.'),
        ),
    ]
